version: '3.7'
services:
  master-hadoop:
    restart: always
    image: n454149301/centos-openssh-openjdk-hadoop:3.2.1
    hostname: hadoop-slave1
    ports:
        # ssh port
        - '10022:10022'
        # zookeeper client
        - '2181:2181'
        # zookeeper follower
        - '2888:2888'
        # zookeeper election
        - '3888:3888'
        # namenode rpc server
        - '9820:9820'
        # namenode http server
        - '9870:9870'
        # journalnode rpc server
        - '8485:8485'
        # journalnode http server
        - '8480:8480'
        # datanode server
        - '9866:9866'
        # yarn server
        - '8032:8032'
        # webhdfs server
        - '9900:9900'
        # jobhistory server
        - '10020:10020'
        # mapreduce_job_client_port_range
        - '50000-50100:50000-50100'
    extra_hosts:
      - "hadoop-master:192.168.1.100"
      - "hadoop-slave2:192.168.1.102"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ./ssh:/root/.ssh
      - ./zookeeper/data:/root/zookeeper/data
      - ./zookeeper/logs:/root/zookeeper/logs
      - ./hadoop/dfs:/root/hadoop/dfs
      - ./hadoop/logs:/root/hadoop/logs
      - ./hadoop/tmp:/root/hadoop/tmp
    command: tail -f /dev/null
